delete from courses;
insert into courses (id, credits, name, teacher_id, exam_date) values (1, 4, 'Mathematical Analysis I', 1, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (2, 4, 'Linear Algebra and Analytic Geometry', 2, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (3, 5, 'Discrete Mathematics',3, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (4, 5, 'Logic Design', 4, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (5, 6, 'Computer Programming', 5, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (6, 4, 'Physics', 6, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (7, 4, 'Mathematical Analysis II', 1, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (8, 6, 'Digital System Design', 7, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (9, 6, 'Data Structures and Algorithms', 8, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (10, 4, 'Assembly Language Programming', 1, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (11, 4, 'Logic Programming', 2, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (12, 4, 'Computer Graphics', 2, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (13, 5, 'Functional Programming',3, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (14, 5, 'Structure of Computing Systems', 4, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (15, 6, 'Software Design', 5, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (16, 4, 'Image Processing', 6, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (17, 4, 'Introduction to Artificial intelligence', 1, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (18, 6, 'Intelligent Systems', 7, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (19, 6, 'Formal Languages and Translators', 8, '06/04/2018');
insert into courses (id, credits, name, teacher_id, exam_date) values (20, 4, 'Fundamental Algorithms', 1, '06/04/2018');