insert into courses (id, credits, name, teacher_id) values (1, 4, 'Mathematical Analysis I', 1);
insert into courses (id, credits, name, teacher_id) values (2, 4, 'Linear Algebra and Analytic Geometry', 2);
insert into courses (id, credits, name, teacher_id) values (3, 5, 'Discrete Mathematics',3);
insert into courses (id, credits, name, teacher_id) values (4, 5, 'Logic Design', 4);
insert into courses (id, credits, name, teacher_id) values (5, 6, 'Computer Programming', 5);
insert into courses (id, credits, name, teacher_id) values (6, 4, 'Physics', 6);
insert into courses (id, credits, name, teacher_id) values (7, 4, 'Mathematical Analysis II', 1);
insert into courses (id, credits, name, teacher_id) values (8, 6, 'Digital System Design', 7);
insert into courses (id, credits, name, teacher_id) values (9, 6, 'Data Structures and Algorithms', 8);
insert into courses (id, credits, name, teacher_id) values (10, 4, 'Assembly Language Programming', 1);
insert into courses (id, credits, name, teacher_id) values (11, 4, 'Logic Programming', 2);
insert into courses (id, credits, name, teacher_id) values (12, 4, 'Computer Graphics', 2);
insert into courses (id, credits, name, teacher_id) values (13, 5, 'Functional Programming',3);
insert into courses (id, credits, name, teacher_id) values (14, 5, 'Structure of Computing Systems', 4);
insert into courses (id, credits, name, teacher_id) values (15, 6, 'Software Design', 5);
insert into courses (id, credits, name, teacher_id) values (16, 4, 'Image Processing', 6);
insert into courses (id, credits, name, teacher_id) values (17, 4, 'Introduction to Artificial intelligence', 1);
insert into courses (id, credits, name, teacher_id) values (18, 6, 'Intelligent Systems', 7);
insert into courses (id, credits, name, teacher_id) values (19, 6, 'Formal Languages and Translators', 8);
insert into courses (id, credits, name, teacher_id) values (20, 4, 'Fundamental Algorithms', 1);